### ISSUE TITLE
Página de Tabela de Serviços do Aeroporto

### ISSUE THREAD

**Issue by alsgu3rra** [aeroportos-onix/dashboard-ui#2]
<a name="readme-top"></a>

## Resumo da Nova Feature

Página para listar todos os serviços cadastrados dentro do aeroporto, esta página deve conter uma tabela simples com os dados de serviços cadastrados de acordo com a tabela de serviços.

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Qual a utilidade da nova Feature

A utilidade é para que o administrador do aeroporto possa visualizar a tabela com seus serviços cadastrados no aeroporto que ele administra

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Roadmap

 
 Add Botão para confirmar cadastro
 Add Campos no Formulário
 Nome do Serviço do tipo texto
 Preço do Serviço do tipo numérico
 Descrição do Serviço do tipo área de texto

- [x] Página html
- [x] Add layout padrão na página
- [x] Add tabela utilizando bootstrap
- [x] Add Colunas na Tabela
    - [x] Nome do Serviço
    - [x] Preço do Serviço
    - [x] Tipo de cobrança do serviço que deve ser por padrão unidade
    - [x] Data formatada de quando o serviço foi cadastrado

<p align="right">(<a href="#readme-top">back to top</a>)</p>
