### ISSUE TITLE
Página de Tabela de Operações de Serviços

### ISSUE THREAD

**Issue by alsgu3rra** [aeroportos-onix/dashboard-ui#3]
---
name: Nova Função
about: Com esse template você poderá Sugerir uma ideia para este projeto ou indique
  algo que estar faltando.
title: "[FEATURE] nome-da-função"
labels: enhancement

---

<a name="readme-top"></a>

## Resumo

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Qual a utilidade da nova Feature

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Roadmap

- [ ] Add Changelog
- [ ] Add back to top links
- [ ] Add Additional Templates w/ Examples
- [ ] Add "components" document to easily copy & paste sections of the readme
- [ ] Multi-language Support
    - [ ] Chinese
    - [ ] Spanish

<p align="right">(<a href="#readme-top">back to top</a>)</p>
