### ISSUE TITLE
Página de erro 404

### ISSUE THREAD

**Issue by alsgu3rra** [aeroportos-onix/dashboard-ui#5]
<a name="readme-top"></a>

## Resumo

Todo site precisa de uma página de erro de conteúdo não encontrado, para isso precisamos criar uma nova página de erro 404. Todos conteúdo que não for encontrado será redirecionado para essa página.

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Qual a utilidade da nova Feature

Esta página tem a utilidade de redirecionar o usuário para uma página de erro. tendo então um "tratamento de erro" ou resposta para o usuário final.

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Roadmap

- [ ] Add Página html
- [ ] Add Container deixando o conteúdo centralizado na tela
- [ ] Add um título de 404
- [ ] Add Subtítulo de erro ao buscar conteúdo
- [ ] Add um texto descritivo do erro
- [ ] Add botão para redirecionar o usuário para página de início

<p align="right">(<a href="#readme-top">back to top</a>)</p>
