### ISSUE TITLE
Página Index

### ISSUE THREAD

**Issue by alsgu3rra** [aeroportos-onix/dashboard-ui#6]
<a name="readme-top"></a>

## Resumo

Esta página literalmente é um template/layout para todas as outras página utilizar como base.

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Qual a utilidade da nova Feature

Esta página é apenas para construir o layout padrão utilizando html, css, javascript, jquery e bootstrap 4.6

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## Roadmap

- [X] Add Página html
- [X] Add Bootstrap, Jquery e Popper.js
- [X] Add Font Awesome e Line Awesome
- [X] Add Layout padrão
- [X] Add Barra de navegação superior
- [X] Add logo do site
- [X] Add Botão para fechar a barra lateral
- [X] Add Suporte aos dispositivos abaixo:
  - [X] Mobile
  - [X] Desktop
- [X] Add Estes itens a barra lateral
    - [X] Menu de cadastrar serviço
    - [X] Menu de tabela de serviços
    - [ ] Menu de tabela de operações

<p align="right">(<a href="#readme-top">back to top</a>)</p>
